name: Manual deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Source to deploy'
        type: string
        required: true
      environment:
        description: 'Environment to deploy the code'
        type: choice
        options:
          - aem-asset-selector.vercel.app

jobs:
  deploy-application:
    uses: ./.github/workflows/csaem-selector-deployment-module.yml
    with:
      environment_name: ${{ inputs.environment }}
      branch: ${{ inputs.tag }}
      deploy_application: true
    secrets:
      VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
      VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
      VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'
